# Generated by Django 4.2.7 on 2024-07-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posarea',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posregion',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
