# Generated by Django 4.2.7 on 2024-07-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpriceinfo',
            old_name='is_show_in_ecommerce',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='productpriceinfo',
            name='is_show_in_pos',
        ),
    ]
