# Generated by Django 4.2.7 on 2024-07-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_rename_is_show_in_ecommerce_productpriceinfo_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpriceinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
