# Generated by Django 4.2.7 on 2024-07-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_alter_productpriceinfo_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpriceinfo',
            name='serial_no',
            field=models.IntegerField(default=2500),
        ),
    ]
