# Generated by Django 4.2.7 on 2024-07-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_productpriceinfo_serial_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpriceinfo',
            name='serial_no',
        ),
        migrations.AddField(
            model_name='product',
            name='serial_no',
            field=models.IntegerField(default=2500),
        ),
    ]
