# Generated by Django 4.2.7 on 2024-07-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('schedule_type', models.CharField(choices=[('DATE_WISE', 'Date Wise'), ('TIME_WISE', 'Time Wise')], default='DATE_WISE', max_length=10)),
                ('amount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat')], default='FLAT', max_length=20)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('discount_type', models.CharField(choices=[('ECOMMERCE_SELL', 'E-Commerce Sell'), ('RETAIL_ECOMMERCE_SELL', 'Retail E-Commerce Sell'), ('POINT_OF_SELL', 'Point of Sell'), ('ON_THE_GO', 'On the Go'), ('CORPORATE_SELL', 'Corporate Sell'), ('B2B_SELL', 'B2B Sell'), ('GIFT_ORDER', 'Gift Order'), ('PC_BUILDER_SELL', 'Pc Builder Order'), ('PRE_ORDER', 'Pre-Order'), ('REPLACEMENT_ORDER', 'Replacement Order')], default='ECOMMERCE_SELL', max_length=100)),
                ('discount_status', models.CharField(choices=[('CAMPAIGN', 'Campaigns'), ('DEAL_OF_WEEK', 'Deal of the week'), ('DISCOUNT', 'Discount')], default='DISCOUNT', max_length=20)),
                ('is_for_lifetime', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=350, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('schedule_type', models.CharField(choices=[('DATE_WISE', 'Date Wise'), ('TIME_WISE', 'Time Wise')], default='DATE_WISE', max_length=10)),
                ('amount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FLAT', 'Flat')], default='FLAT', max_length=20)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('promo_type', models.CharField(choices=[('ECOMMERCE_SELL', 'E-Commerce Sell'), ('RETAIL_ECOMMERCE_SELL', 'Retail E-Commerce Sell'), ('POINT_OF_SELL', 'Point of Sell'), ('ON_THE_GO', 'On the Go'), ('CORPORATE_SELL', 'Corporate Sell'), ('B2B_SELL', 'B2B Sell'), ('GIFT_ORDER', 'Gift Order'), ('PC_BUILDER_SELL', 'Pc Builder Order'), ('PRE_ORDER', 'Pre-Order'), ('REPLACEMENT_ORDER', 'Replacement Order')], default='ECOMMERCE_SELL', max_length=150)),
                ('is_for_lifetime', models.BooleanField(default=False)),
                ('is_for_all', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('minimum_purchase_amount', models.FloatField(default=0.0)),
                ('maximum_purchase_amount', models.FloatField(default=0.0)),
                ('maximum_use_limit', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('total_apply', models.IntegerField(default=0)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
