# Generated by Django 4.2.7 on 2024-07-09 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HookProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('serial_no', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopDayEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('total_sell_amount', models.FloatField(default=0.0)),
                ('retail_sell_amount', models.FloatField(default=0.0)),
                ('retail_gsheba_sell_amount', models.FloatField(default=0.0)),
                ('panel_partnership', models.JSONField(blank=True, null=True)),
                ('e_retail_sell_amount', models.FloatField(default=0.0)),
                ('ecommerce_collection_amount', models.FloatField(default=0.0)),
                ('corporate_sell_amount', models.FloatField(default=0.0)),
                ('refund_amount', models.FloatField(default=0.0)),
                ('warranty_claim_quantity', models.FloatField(default=0.0)),
                ('gsheba_claim_quantity', models.FloatField(default=0.0)),
                ('total_b2b_sell_amount', models.FloatField(default=0.0)),
                ('mfs_collection', models.JSONField(blank=True, null=True)),
                ('currency_collection', models.JSONField(blank=True, null=True)),
                ('total_bank_deposit_amount', models.FloatField(default=0.0)),
                ('total_expense_amount', models.FloatField(default=0.0)),
                ('petty_cash_amount', models.FloatField(default=0.0)),
                ('opening_balance_amount', models.FloatField(default=0.0)),
                ('current_balance_amount', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('day_end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopDayEndMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_message_send', models.BooleanField(default=True)),
                ('is_mail_send', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopPanelHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=150)),
                ('serial_no', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('serial_no', models.IntegerField(default=1)),
                ('is_popup', models.BooleanField(default=False)),
                ('is_slider', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sliders', to='product_management.category')),
            ],
        ),
    ]
