# Generated by Django 4.2.7 on 2024-10-20 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EscalateIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(max_length=10, unique=True)),
                ('issue_create_date', models.DateTimeField(auto_now_add=True)),
                ('days_passed', models.IntegerField(default=0)),
                ('subject', models.CharField(max_length=255)),
                ('issue_details', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SOLVED', 'Solved'), ('UNSOLVED', 'Unsolved')], default='PENDING', max_length=10)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_department', to='reports.department')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to=settings.AUTH_USER_MODEL)),
                ('to_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_department', to='reports.department')),
            ],
        ),
    ]
