# Generated by Django 4.2.7 on 2024-10-20 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_rename_department_escalateissuedepartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalateissue',
            name='action_taken',
        ),
        migrations.AddField(
            model_name='escalateissue',
            name='assigned_people',
            field=models.ManyToManyField(blank=True, related_name='assigned_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escalateissue',
            name='issue_id',
            field=models.CharField(default='FC61421939', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='escalateissue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SOLVED', 'Solved'), ('FORWARDED', 'Forwarded'), ('UNSOLVED', 'Unsolved')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='escalateissue',
            name='to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_department', to='reports.escalateissuedepartment'),
        ),
        migrations.CreateModel(
            name='IssueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.TextField()),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_by', to=settings.AUTH_USER_MODEL)),
                ('forwarded_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_department', to='reports.escalateissuedepartment')),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_to', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_actions', to='reports.escalateissue')),
            ],
        ),
    ]
