# Generated by Django 4.2.7 on 2024-10-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_escalateissue_action_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalateissue',
            name='issue_id',
            field=models.CharField(default='4AFAE0E2A8', max_length=10, unique=True),
        ),
    ]
