# Generated by Django 4.2.7 on 2024-07-09 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resource_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_created_s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ranking',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rankings', to='human_resource_management.grading'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranking_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobexperienceinformation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_experience_information_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobexperienceinformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_experience_information_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grading',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grading',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examtype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_type_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examtype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_type_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_type_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_type_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventornotice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_or_notice_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventornotice',
            name='employee',
            field=models.ManyToManyField(blank=True, related_name='event_or_notices', to='human_resource_management.employeeinformation'),
        ),
        migrations.AddField(
            model_name='eventornotice',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_or_notices', to='human_resource_management.eventtype'),
        ),
        migrations.AddField(
            model_name='eventornotice',
            name='office_location',
            field=models.ManyToManyField(blank=True, related_name='event_or_notices', to='location.officelocation'),
        ),
        migrations.AddField(
            model_name='eventornotice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_or_notice_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeetype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_type_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeetype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_type_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeetaskstatuslog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_task_status_log_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeetaskstatuslog',
            name='employee_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_task_status_logs', to='human_resource_management.employeetask'),
        ),
        migrations.AddField(
            model_name='employeetaskstatuslog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_task_status_log_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by_employee_tasks', to='human_resource_management.employeeinformation'),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_task_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_tasks', to='human_resource_management.employeeinformation'),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_task_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeofficehour',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_office_hour_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeofficehour',
            name='employee_information',
            field=models.ManyToManyField(blank=True, related_name='employee_office_hours', to='human_resource_management.employeeinformation'),
        ),
        migrations.AddField(
            model_name='employeeofficehour',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_office_hour_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeinformationlog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_information_log_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeinformationlog',
            name='employee_designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_information_logs', to='human_resource_management.designation'),
        ),
        migrations.AddField(
            model_name='employeeinformationlog',
            name='employee_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_information_logs', to='human_resource_management.employeeinformation'),
        ),
        migrations.AddField(
            model_name='employeeinformationlog',
            name='employee_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_information_logs', to='human_resource_management.ranking'),
        ),
        migrations.AddField(
            model_name='employeeinformationlog',
            name='employee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_information_logs', to='human_resource_management.employeetype'),
        ),
        migrations.AddField(
            model_name='employeeinformationlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_information_log_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='bank_information',
            field=models.ManyToManyField(blank=True, related_name='employee_informations', to='human_resource_management.bankinformation'),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_information_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='designations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_informations', to='human_resource_management.designation'),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='employee_address_information',
            field=models.ManyToManyField(blank=True, related_name='employee_informations', to='human_resource_management.employeeaddressinformation'),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='employee_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_informations', to='base.company'),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='employee_education_information',
            field=models.ManyToManyField(blank=True, related_name='employee_informations', to='human_resource_management.employeeeducationinformation'),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='employee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_informations', to='human_resource_management.employeetype'),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='guardian_information',
            field=models.ManyToManyField(blank=True, related_name='employee_informations', to='human_resource_management.employeeguardianinformation'),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='job_experience_information',
            field=models.ManyToManyField(blank=True, related_name='employee_informations', to='human_resource_management.jobexperienceinformation'),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='pos_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_informations', to='location.posarea'),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='pos_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_informations', to='location.posregion'),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_informations', to='human_resource_management.ranking'),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='reporting_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_informations', to='human_resource_management.employeeinformation'),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_information_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_informations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeinformation',
            name='work_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_informations', to='location.officelocation'),
        ),
        migrations.AddField(
            model_name='employeeguardianinformation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_guardian_information_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeguardianinformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_guardian_information_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeeducationinformation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_education_information_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeeducationinformation',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_education_informations', to='human_resource_management.examtype'),
        ),
        migrations.AddField(
            model_name='employeeeducationinformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_education_information_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedivision',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_division_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedivision',
            name='division_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_divisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedivision',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_division_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeecalendar',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_calendar_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeecalendar',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_calendars', to='human_resource_management.employeeinformation'),
        ),
        migrations.AddField(
            model_name='employeecalendar',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_calendars', to='human_resource_management.eventtype'),
        ),
        migrations.AddField(
            model_name='employeecalendar',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_calendar_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeattendancelog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance_log_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeattendancelog',
            name='employee_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_attendance_logs', to='human_resource_management.employeeattendance'),
        ),
        migrations.AddField(
            model_name='employeeattendancelog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance_log_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_attendance_approved_bys', to='human_resource_management.employeeinformation'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='employee_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_attendances', to='human_resource_management.employeeinformation'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='employee_office_hour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_attendances', to='human_resource_management.employeeofficehour'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeaddressinformation',
            name='area_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_address_informations', to='location.area'),
        ),
        migrations.AddField(
            model_name='employeeaddressinformation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_address_information_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeaddressinformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_address_information_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designation',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='human_resource_management.department'),
        ),
        migrations.AddField(
            model_name='designation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='employee_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='human_resource_management.employeedivision'),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankinformation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_information_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankinformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_information_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
    ]
