# Generated by Django 4.2.7 on 2024-07-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='attendance_type',
            field=models.CharField(choices=[('ON_TIME', 'On Time'), ('OVER_TIME', 'Over Time'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('CASUAL_LEAVE', 'Casual Leave'), ('SICK_LEAVE', 'Sick Leave'), ('SPECIAL_LEAVE', 'Special Leave'), ('PATERNITY_LEAVE', 'Paternity Leave'), ('MATERNITY_LEAVE', 'Maternity Leave'), ('EXTRA_OFFICE_DAY', 'Extra Office Day')], default='ON_TIME', max_length=20),
        ),
    ]
