# Generated by Django 4.2.7 on 2024-10-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_management', '0002_log_purchase_specification_delete_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='value',
        ),
        migrations.AlterField(
            model_name='log',
            name='log_json',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='specification',
        ),
        migrations.AlterField(
            model_name='specification',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='specification',
            field=models.JSONField(default=list),
        ),
    ]
