# Generated by Django 4.2.7 on 2024-10-30 09:23

from django.db import migrations, models

from django.utils import timezone
class Migration(migrations.Migration):

    dependencies = [
        ('purchase_management', '0003_remove_specification_value_alter_log_log_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='comment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
