# Generated by Django 4.2.7 on 2024-10-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_management', '0004_purchase_comment_purchase_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
