# Generated by Django 4.2.7 on 2024-10-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_management', '0005_alter_purchase_created_at_alter_purchase_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='updated_at',
        ),
    ]
