# Generated by Django 4.2.7 on 2024-10-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_management', '0009_logentry_product_remove_purchase_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='required_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
