# Generated by Django 4.2.7 on 2024-10-31 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_management', '0010_product_required_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_logentries_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
