# Generated by Django 4.2.7 on 2024-11-04 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_management', '0011_logentry_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('required_qty', models.PositiveIntegerField()),
                ('vendor', models.CharField(max_length=100)),
                ('previous_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('required_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_data', to='purchase_management.purchase')),
            ],
        ),
    ]
