# Generated by Django 4.2.7 on 2024-11-05 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_management', '0014_purchasepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
