# Generated by Django 4.2.7 on 2024-11-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_management', '0016_purchasepayment_paid_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('card', 'Card'), ('bkash', 'Bkash'), ('rocket', 'Rocket'), ('nagad', 'Nagad')], default='cash', max_length=16),
        ),
    ]
