# Generated by Django 4.2.7 on 2024-07-09 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('product_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_initial'),
        ('location', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicingorderstatuslog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicing_order_status_log_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicingorderstatuslog',
            name='servicing_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicing_order_status_logs', to='order.servicingorder'),
        ),
        migrations.AddField(
            model_name='servicingorderstatuslog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicing_order_status_log_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicingorderitemstatuslog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicing_order_item_status_log_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicingorderitemstatuslog',
            name='servicing_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicing_order_item_status_logs', to='order.servicingorderitem'),
        ),
        migrations.AddField(
            model_name='servicingorderitemstatuslog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicing_order_item_status_log_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicingorderitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicing_order_item_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicingorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicing_order_items', to='product_management.product'),
        ),
        migrations.AddField(
            model_name='servicingorderitem',
            name='servicing_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicing_order_items', to='order.servicingorder'),
        ),
        migrations.AddField(
            model_name='servicingorderitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicing_order_item_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicingorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicing_order_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicingorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicing_orders', to='order.order'),
        ),
        migrations.AddField(
            model_name='servicingorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicing_order_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreview',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreview',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to='order.order'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to='product_management.product'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_review_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_status_log_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_logs', to='order.order'),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_status_log_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderpaymentlog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_log_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderpaymentlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payment_logs', to='order.order'),
        ),
        migrations.AddField(
            model_name='orderpaymentlog',
            name='order_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payment_logs', to='base.paymenttype'),
        ),
        migrations.AddField(
            model_name='orderpaymentlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_log_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitemwarrantylog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_warranty_log_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitemwarrantylog',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_warranty_logs', to='order.orderitem'),
        ),
        migrations.AddField(
            model_name='orderitemwarrantylog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_warranty_log_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitemstatuslog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_status_log_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitemstatuslog',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_status_logs', to='order.orderitem'),
        ),
        migrations.AddField(
            model_name='orderitemstatuslog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_status_log_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='order.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='product_management.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderhistorylog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history_log_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderhistorylog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history_logs', to='order.order'),
        ),
        migrations.AddField(
            model_name='orderhistorylog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_history_log_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='location.area'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='user.userinformation'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.deliverymethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_shop_orders', to='location.officelocation'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_shop_orders', to='location.officelocation'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='location.officelocation'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_method_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_method_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeraddressinfolog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_address_log_created_bys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeraddressinfolog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_address_logs', to='order.order'),
        ),
        migrations.AddField(
            model_name='customeraddressinfolog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_address_log_updated_bys', to=settings.AUTH_USER_MODEL),
        ),
    ]
