# Generated by Django 4.2.7 on 2024-07-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_customeraddressinfolog_secondary_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('ORDER_RECEIVED', 'Order Received'), ('PRODUCT_AVAILABILITY_CHECK', 'Product Availability Check'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('PRODUCT_PURCHASED', 'Product Purchased'), ('PRELIMINARY_QC', 'Preliminary QC'), ('DETAILED_QC', 'Detailed QC'), ('PACKAGED', 'Packaged'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('IN_TRANSIT', 'In Transit'), ('DISPATCHED', 'Dispatched'), ('SHOP_DELIVERY_IN_TRANSIT', 'Shop Delivery in Transit'), ('SHOP_RECEIVED', 'Shop Received'), ('DELIVERED_TO_CUSTOMER', 'Delivered To Customer'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned'), ('GSHEBA_RETURNED', 'G-Sheba Returned'), ('REFUNDED', 'Refunded'), ('SHOP_TO_WAREHOUSE', 'Shop to Warehouse'), ('WAREHOUSE_RECEIVED', 'Warehouse Received'), ('WAREHOUSE_TO_SERVICE_POINT', 'Warehouse to Service Point'), ('SERVICE_POINT_RECEIVED', 'Service Point Received'), ('WAREHOUSE_TO_VENDOR', 'Warehouse to Vendor'), ('IN_SERVICING', 'In Servicing'), ('SERVICE_POINT_TO_WAREHOUSE', 'Service Point to Warehouse'), ('OTHERS', 'Others')], default='ORDER_RECEIVED', max_length=550),
        ),
    ]
