# Generated by Django 4.2.7 on 2024-07-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_customeraddressinfolog_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemwarrantylog',
            name='warranty_type',
            field=models.CharField(choices=[('1_GSHEBA_WARRANTY', 'Gsheba'), ('2_COMPANY_WARRANTY', 'Company Warranty'), ('3_REPLACEMENT_WARRANTY', 'Replacement Warranty'), ('4_SERVICE_WARRANTY', 'Service Warranty'), ('5_SUPPLIER_SERVICE_WARRANTY', 'Supplier Warranty')], default='GSHEBA_WARRANTY', max_length=30),
        ),
    ]
